config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  root "users#show"

  get 'user/withdraw_money', to: 'users#withdraw_money'
  patch 'user/withdraw_money', to: 'users#after_withdraw_money'
  get 'user/transfer_to_another_user', to: 'users#transfer_to_another_user'
  patch 'user/after_transfer_to_another_user', to: 'users#after_transfer_to_another_user'

  get 'transaction_reports', to: 'users#transaction_reports'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	validates :username, presence: true
	validates :wallet, :numericality => { :greater_than_or_equal_to => 0 }
	has_many :transactions, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :wallet, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  	def show
  		@users = User.where.not(id: current_user.id)
  		@user = User.find_by_id(current_user.id)
	end

	def withdraw_money
		@user = User.find_by_id(params[:id])
	end

	def after_withdraw_money
		amount = current_user.wallet
		if params[:wallet].to_f <= amount
			amount -= params[:wallet].to_f
			current_user.update_attributes(:wallet => amount)
			Transaction.create(user_id: current_user.id, amount: params[:wallet].to_f, transaction_type: "wallet withdraw money", transaction_note: "#{amount} minus by #{params[:wallet].to_f}")
			flash[:notice] = "your wallet amount is debited!"
			redirect_to user_path(current_user.id)
		else
			flash[:alert] = "Alerting...... its not possible"
			redirect_to user_withdraw_money_path(:id => current_user.id)
		end
	end

	
	def transfer_to_another_user
		@user = User.find_by_id(params[:id])
		@users = User.where.not(id: params[:id])
	end

	def after_transfer_to_another_user
		@user = User.find_by_id(params[:transfer_to_user])
		amount = current_user.wallet
		if params[:wallet].to_f <= amount
			amount -= params[:wallet].to_f
			current_user.update_attributes(:wallet => amount)
			@user.update_attributes(:wallet => (@user.wallet + params[:wallet].to_f))
			Transaction.create(user_id: current_user.id, amount: params[:wallet].to_f, transaction_type: "transfer_to another user money", transaction_note: "#{amount} minus by #{params[:wallet].to_f}")
			flash[:notice] = "your wallet amount is debited!"
			redirect_to user_path(current_user.id)
		else
			flash[:alert] = "Alerting...... its not possible"
			redirect_to user_transfer_to_another_user_path(:id => current_user.id)
		end
	end

	def transaction_reports
		@transaction = Transaction.where(user_id: params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BotreeTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <div class="container">
    <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
  <li>
  <%= link_to "Edit Profile Or Add wallet Amount", edit_user_registration_path %>   
  </li>
    <li>
  <%= link_to "Go to Root", user_path(current_user.id) %>   
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Wallet</th>
    <th>Withdraw money</th>
    <th>Transfer to another user</th>
    <th>Transaction Reports</th>
  </tr>
  <tr>
    <td><%= @user.try(:username)%></td>
    <td><%= @user.try(:email)%></td>
    <td><%= @user.try(:wallet)%></td>
    <td><%= link_to('Withdraw money', user_withdraw_money_path(:id => @user.id)) %>    </td>
    <td>
      <% if @users.present? && @users > 1 %>
        <%= link_to('Transfer to another user', user_transfer_to_another_user_path(:id => @user.id)) %>    
      <%else%>
        When other users is present
      <%end %>
      </td>

    <td><%= link_to('Transaction Reports', transaction_reports_path(:id => @user.id)) %></td>
  </tr>
</table>

app/views/users/transaction_reports.html.erb
<table>
  <tr>
    <th>User Name</th>
    <th>Email</th>
    <th>Deduct Amount</th>
    <th>Date</th>
    <th>Transaction Type</th>
    <th>Transaction Note</th>
  </tr>
<% if @transaction.present? %>  
  <% @transaction.each do |tans| %>  
    <tr>
      <td><%= tans.user.try(:username)%></td>
      <td><%= tans.user.try(:email)%></td>
      <td><%= tans.try(:amount)%></td>
      <td><%= tans.try(:created_at).to_date%></td>
      <td><%= tans.try(:transaction_type)%></td>
      <td><%= tans.try(:transaction_note)%></td>
    </tr>
  <% end %>
<% else %>
  <td colspan="4">Not transaction present.</td>
<% end %>

</table>

app/views/users/transfer_to_another_user.html.erb
<%= form_for @user, :url => {:controller => "users", :action => "after_transfer_to_another_user"} do |f| %>

  <div class="form-group">
    <%= f.label "In Wallet amount" %>
    <%= f.number_field :wallet, autofocus: true, autocomplete: 'wallet', class: 'form-control', :readonly => true%>
  </div>

  <div class="form-group">
    <%= f.label :wallet %>
    <%= number_field_tag :wallet, autofocus: true, autocomplete: 'wallet', class: 'form-control' %>
  </div>

<div class="form-group">
    <%= f.label :transfer_to_user %>
    <%= select_tag 'transfer_to_user', options_for_select(@users.collect{ |u| [u.username, u.id] }), autofocus: true, autocomplete: 'wallet', class: 'form-control' %>
  </div>
  

  <div class="form-group">
    <%= f.submit 'deduct amount', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/withdraw_money.html.erb
<%= form_for @user, :url => {:controller => "users", :action => "after_withdraw_money"} do |f| %>

  <div class="form-group">
    <%= f.label "In Wallet amount" %>
    <%= f.number_field :wallet, autofocus: true, autocomplete: 'wallet', class: 'form-control', :readonly => true%>
  </div>

  <div class="form-group">
    <%= f.label :wallet %>
    <%= number_field_tag :wallet, autofocus: true, autocomplete: 'wallet', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'deduct amount', class: 'btn btn-primary' %>
  </div>
<% end %>